language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
# don't waste CI cycles
#  - 7
#  - hhvm

env:
  matrix:
    - DB=mysql OWNCLOUD=master

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
  include:
    - php: 5.4
      env: DB=sqlite OWNCLOUD=master
    - php: 5.4
      env: DB=pgsql OWNCLOUD=master
    - php: 5.4
      env: DB=mysql OWNCLOUD=stable8.1
    - php: 5.4
      env: DB=mysql OWNCLOUD=stable8
    - php: 5.4
      env: DB=mysql OWNCLOUD=stable7
  fast_finish: true

branches:
  only:
    - master
    - albumartist_test

before_install:
  - cd ..
  - git clone https://github.com/owncloud/core.git --depth 1 -b $OWNCLOUD
  - mv music core/apps/
  - cd core
  - git submodule update --init
  # startup php server
  - php -S localhost:8888 -t . &
  # provisioning the database
  - mysql -u root -e "CREATE DATABASE oc_autotest; CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY 'oc_autotest'; GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"
  - psql -U postgres -w -c "CREATE DATABASE oc_autotest;"
  - psql -U postgres -w -c "CREATE USER oc_autotest WITH PASSWORD 'oc_autotest'; GRANT ALL PRIVILEGES ON DATABASE oc_autotest TO oc_autotest;"
  # setup ownCloud
  - apps/music/build/setup.sh $OWNCLOUD $DB oc_autotest oc_autotest oc_autotest admin admin
  # TODO remove once stable7 is not supported anymore
  - bash -c "if [ '$OWNCLOUD' == 'stable7' ]; then sed -i '461 s/self/#self/' lib/base.php; fi"
  - ./occ app:enable music
  - apps/music/build/addUser.sh $OWNCLOUD ampache ampache
  # download test data (only if not cached already)
  - apps/music/tests/downloadTestData.sh data/ampache
  - ./occ files:scan ampache
  - ./occ music:scan ampache
  # TODO remove once stable7 is not supported anymore
  - bash -c "if [ '$OWNCLOUD' == 'stable7' ]; then sed -i '461 s/#self/self/' lib/base.php; fi"
  # add Ampache API key with ampache as password for user ampache
  - bash -c "if [ '$DB' == 'sqlite' ]; then sqlite3 data/owncloud.db 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'mysql' ]; then mysql -u oc_autotest -poc_autotest oc_autotest -e 'INSERT INTO oc_music_ampache_users (user_id, hash) VALUES (\"ampache\", \"3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18\");'; fi"
  - bash -c "if [ '$DB' == 'pgsql' ]; then psql -U postgres -d oc_autotest -w -c \"INSERT INTO oc_music_ampache_users (user_id, hash) VALUES ('ampache', '3e60b24e84cfa047e41b6867efc3239149c54696844fd3a77731d6d8bb105f18');\"; fi"
  - cd apps/music

install:
  - composer install
  - cp tests/behat.yml.travis tests/behat.yml

script:
  - phpunit --coverage-clover clover-unit.xml --configuration tests/php/unit/phpunit.xml tests/php/unit
  - phpunit --coverage-clover clover-integration.xml --configuration tests/php/integration/phpunit.xml tests/php/integration
  - cd tests && ../vendor/bin/behat

  # Create coverage report
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '5.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '5.4' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-unit.xml; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == '5.4' ]; then php ocular.phar code-coverage:upload --format=php-clover ../clover-integration.xml; fi"

  # debug section to check what went wrong
  - curl http://admin:admin@localhost:8888/index.php
  - curl http://admin:admin@localhost:8888/index.php/apps/music/
  - cat ../../../data/owncloud.log

cache:
  directories:
    /tmp/downloadedData

